### ISSUE TITLE
warmup control option ignored

### ISSUE THREAD

**Issue by louisaslett** [joshuaulrich/microbenchmark#46]
### Description

The `warmup` control option seems to be ignored.

### Expected behavior

The `warmup` control option should run the code a certain number of times prior to the timed runs.

### Minimal, reproducible example

```r
system.time(microbenchmark(Sys.sleep(1), times = 2, control = list(warmup = 5L)))
```

The above code shows an elapsed time of about 2 seconds.  If there were 5 warmup iterations being run, the elapsed time would be nearer to 7 seconds.

### Session Info

```r
R version 4.3.1 (2023-06-16)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.5.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

time zone: Europe/Dublin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] microbenchmark_1.4.10

loaded via a namespace (and not attached):
[1] compiler_4.3.1
```

**Comment by tinygreen** [comment]
Looking at the C code, it does not seem to be ignored, it just doesn't do what OP expects, because the documentation is vague.

The option is documented as ```the number of warm-up iterations performed before the actual benchmark.``` But these are not iterations of the expressions to be timed, they are iterations of ```do_nothing()```, which is a function that just returns the value 42. The time spent by these calls is ```used to estimate the timing overhead```, which is later subtracted from the time spent by the expressions that are actually timed.

The documentation claims that the calls to ```do_nothing()``` also have the effect of ```spinning up the processor from any sleep or idle states it might be in```, but I don't know if a couple of calls to a function that just does ```return 42;``` is sufficient for that.

This part of the documentation should probably be clarified:
https://github.com/joshuaulrich/microbenchmark/blob/676130d11f6f1c31cfd7c68d3a319a5c00ab6aba/R/microbenchmark.R#L26-L29

**Comment by joshuaulrich** [comment]
@tinygreen Thanks for the feedback! What do you think of this update to the docs?

> warmup: the number of iterations to run the timing code before
> evaluating the expressions in '...'. These warm-up iterations are used
> to estimate the timing overhead as well as spinning up the processor
> from any sleep or idle states it might be in. The default value is 2.

I'd appreciate any other suggestions you have. Thanks1

**Comment by tinygreen** [comment]
@joshuaulrich Good start! I only suggest a small change in the first line:
> warmup: the number of dry runs of the timing function before
> evaluating the expressions in '...'. These warm-up iterations are used
> to estimate the timing overhead as well as spinning up the processor
> from any sleep or idle states it might be in. The default value is 2.
