### ISSUE TITLE
Package not available for R 3.4.1?

### ISSUE THREAD

**Issue by YijunXie** [joshuaulrich/microbenchmark#6]
Hi I am trying to install microbenchmark on a remote server which only has R 3.4.1 installed. I tried every way I can come up with, but it keeps telling me that "Package 'mcirobenchmark' is not available  (for R version 3.4.1)". Thanks a lot for any advice.

**Comment by joshuaulrich** [comment]
Before getting to your problem, I want you to know that I'm closing this because there's nothing I can change in the package that will fix your problem. I use this tracker to organize bugs and features, not as a support forum. So, no hard feelings... I'm simply trying to stay organized.

Off the top of my head: try a different CRAN mirror.  If that doesn't work, search for the error on Google and/or StackOverflow, but without the package name.
